name = "Craft Nectar Revived"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d87f07f679d9cb531906632d691e3a6725d899a299010a854158cf69efb32063"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
