name = "Craft Nectar Revived"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8682ed9e78e450dbe231ff823529ce1edcbfe576e57be1189514670f443626a"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
