name = "Craft Nectar Revived"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e93b9294235b585490e6958eb899a021c3e67e07dd1554ef204dde8c62134919"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
