name = "Craft Nectar Revived"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "535847ee1f61879e0b63691125232b49902d14c165dca4572c866e9f03934f6a"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
