name = "Craft Nectar Revived"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51ed2f91743ca6ad278c4c9fce9e69184dc5cc9459e73d645a3e23c4d635396b"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
