name = "Craft Nectar Revived"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "35f5421f298018811b93165506d3ec9e6937d52ecbaddc4c45e69947f114b4fe"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
