name = "Craft Nectar Revived"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36820fb2ce6da7354c13e552833137adbd1737e7d33e8cc7c4c5308c012a04b3"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
