name = "Craft Nectar Revived"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fa6491d4b3418fde696aa5a1cbe2540d519aec10e419bf262fe3a4fe74f35f6"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
