name = "Craft Nectar Revived"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa895501d9b7d5a8ef912ad654b15fe701203c5b5a8c6ccb70b02edbaa68f29d"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
