name = "Craft Nectar Revived"
author = "Sewdohe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9bbea5e2cc8fac25cc3cbcf8de47b0aac6affa029504e9f4074d06056b30db3"

[versions]
fabric = "0.16.5"
minecraft = "1.20.1"
